### ISSUE TITLE
BRepAlgoAPI_Fuse missing methods inherited from BOPAlgo_Options

### ISSUE THREAD

**Issue by michaelgale** [CadQuery/OCP#10]
I've been experimenting with the OCP branch of CadQuery and testing my homegrown CQ modelling tools.  Some of my tools access methods directly in the OCE / OCCT kernel.  In particular for "fuzzy" boolean fuse operations, I require setting the fuzzy tolerance value in OCCT.  In OCCT <7.0, `SetFuzzyValue` was inherited by `BRrepAlgo_Fuse`, in versions >=7.4, it appears it is a protected member of `BOPAlgo_Options` and therefore is not exposed in the rendered OCP API.  

Is this a deliberate omission, or has access to adjustable "fuzzy" boolean fuse operations just an artifact of pywrap?  It also looks like the OCP branch of CQ has the fuzzy tolerance commented out of the `fuse` (_bool_op) method in `occ_impl/shapes.py`.

**Comment by adam-urbanczyk** [comment]
It is already solved, use the latest binary from the azure pipeline. I'm setting up automated conda uploads but int will take a couple of days.

**Comment by michaelgale** [comment]
That's great news, thank you.  In the meantime, I've been using a workaround of setting up a generic `BOPAlgo_BOP` class with a Fuse operation which exposes the `SetFuzzyValue` method.

**Comment by michaelgale** [comment]
@adam-urbanczyk FYI, based on my preliminary integration of CQ with OCCT 7.4 / OCP, I am seeing unbelievable performance gains!  For example, one complex model that would take almost 30 minutes to render, now takes 3.5 minutes!  Furthermore, I am seeing less "fragility" of boolean operations which would result in 3D solids disintegrating or with ugly artifacts.  The migration to 7.x OCCT is well worth it.

**Comment by adam-urbanczyk** [comment]
Glad to hear @michaelgale , part of the gain could also be from https://github.com/CadQuery/cadquery/pull/312

**Comment by adam-urbanczyk** [comment]
`SetFuzzyValue` and related are available in the latest conda build.
