### ISSUE TITLE
cadquery-ocp overwrites vtkmodules

### ISSUE THREAD

**Issue by akaszynski** [CadQuery/OCP#109]
### Issue

Installing [cadquery-ocp](https://pypi.org/project/cadquery-ocp/) from PyPI silently overwrites `vtkmodules`, which might conflict with an existing installation of `vtk`. Here's a minimum working example that demonstrates this behavior:

```
$ python -m venv ocp-venv
$ source ocp-venv/bin/activate
$ pip install vtk==9.2.6
$ pip install cadquery-ocp==7.7.0
$ python -c "import vtk"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/ocp-venv/lib/python3.10/site-packages/vtk.py", line 5, in <module>
    from vtkmodules.vtkWebCore import *
ImportError: Initialization failed for vtkWebCore, not compatible with vtkmodules.vtkCommonCore
```

### Suggested Resolution
Require `vtk` when installing `cadquery-ocp`. It seems you'll have to pin the version of `vtk`.

**Comment by jmwright** [comment]
The cadquery-ocp wheel is maintained separately from OCP.

https://github.com/CadQuery/ocp-build-system

Please file this issue on that repo.
