### ISSUE TITLE
Merged lib

### ISSUE THREAD

**Issue by zignig** [CadQuery/OCP#11]
Is it possible to merge  the cadquery with the ocp binaries to make a single .so with all the references ?

**Comment by adam-urbanczyk** [comment]
If I understand you correctly you'd like to embed CQ code in the OCP so file. I think it could be done using some pybind11 tricks https://pybind11.readthedocs.io/en/master/advanced/pycpp/utilities.html#evaluating-python-expressions-from-strings-and-files but I never done it.

**Comment by zignig** [comment]
I just thought it would be cool to have a single binary for distribution.
