### ISSUE TITLE
Expose IMeshTools

### ISSUE THREAD

**Issue by brhubbar** [CadQuery/OCP#142]
As always, thank you for CadQuery and for your continued efforts to make Open CASCADE accessible.

In running STL exports, I have run into situations where the available numeric constructor for [`BRepMesh_IncrementalMesh`](https://dev.opencascade.org/doc/refman/html/class_b_rep_mesh___incremental_mesh.html) used by [`Shape.exportStl`](https://github.com/CadQuery/cadquery/blob/master/cadquery/occ_impl/shapes.py#L447-L449) is insufficient for producing accurate meshes on certain regular surfaces. Instead, an [`IMeshTools_Parameters`](https://dev.opencascade.org/doc/refman/html/struct_i_mesh_tools___parameters.html) specifying more intensive algorithms is necessary. Making this change allows me to exercise control over deviations from faces, rather than edges ([as described here](https://dev.opencascade.org/doc/overview/html/occt_user_guides__mesh.html#occt_modalg_11_2)), which seems to matter in cases like the one I demonstrate below. I've been able to verify that using these advanced settings is sufficient to clean up my mesh by using [`pythonocc_core`](https://github.com/tpaviot/pythonocc-core/blob/master/src/SWIG_files/wrapper/IMeshTools.pyi). However, my entire toolchain is built on CadQuery, so I don't like the idea of swapping dependencies.

I'm unclear how difficult it would be to expose IMeshTools, so this is an ask that you explore making that available in OCP.

## To Reproduce

Run this script:

```py
"""Cut a  curved, filleted surface out of a base tool to demonstrate meshing challenges."""
import cadquery as cq

# It's easier to visualize from a negative, but it is present on positive fillets as well.
base = (
    cq.Workplane("XZ")
    .box(200, 20, 200)
)
tool = (
    cq.Workplane("XZ")
    .moveTo(100, 0)
    .rect(50, 10, False)
    .revolve(360, (0, 0, 0), (0, 1, 0))
    .fillet(0.5)
)
base = base.cut(tool)
base.findSolid().exportBrep('for-occ.brep')
base.findSolid().exportStl('demo.stl')
```

View the STL in a viewer such as [CAD Assistant](https://dev.opencascade.org/project/cad-assistant) to view the result. Changing the exposed mesh settings changes the exact manifestation of the artifacts, but not their nature

![image](https://github.com/CadQuery/OCP/assets/55867501/f37ef687-78d2-49dd-b77c-af748de3d597)

Switching to pythonocc-core to re-export allows use of more advanced controls for a cleaner resulting mesh.

```py
"""Using pythonocc-core because it exposes IMeshTools."""
from OCC.Core.IMeshTools import (
    IMeshTools_Parameters,
    IMeshTools_MeshAlgoType_Watson,
    IMeshTools_MeshAlgoType_Delabella,
)
from OCC.Core.TopoDS import TopoDS_Shape
from OCC.Core.BRep import BRep_Builder
from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh
from OCC.Core.BRepTools import breptools
from OCC.Core.StlAPI import StlAPI_Writer

def main():
    base = importBrep('for-occ.brep')
    params = IMeshTools_Parameters()
    # Basic settings, CQ defaults
    params.Angle  = 1e-3
    params.Deflection  = 0.1
    params.InParallel  = True
    params.Relative  = True
    # Advanced settings.
    params.MeshAlgo = IMeshTools_MeshAlgoType_Delabella
    # params.AngleInterior =
    # params.DeflectionInterior =
    # params.MinSize =
    # params.InternalVerticesMode =
    # params.ControlSurfaceDeflection =
    # params.EnableControlSurfaceDeflectionAllSurfaces =
    # params.CleanModel =
    # params.AdjustMinSize =
    # params.ForceFaceDeflection =
    # params.AllowQualityDecrease =
    exportStl(s, 'with-occ.stl', params)
    # exportStl(s, 'with-occ.stl', 1e-3, 0.1, True, True)


# Essentially copies from CadQuery source
def importBrep(f: str):
    """
    Import shape from a BREP file
    """
    s = TopoDS_Shape()
    builder = BRep_Builder()

    breptools.Read(s, f, builder)

    if s.IsNull():
        raise ValueError(f"Could not import {f}")

    return s

def exportStl(s: TopoDS_Shape, f: str, *args):
    BRepMesh_IncrementalMesh(s, *args)

    writer = StlAPI_Writer()
    writer.SetASCIIMode(False)
    return writer.Write(s, f)

if __name__ == "__main__":
    main()

```

Even just switching the meshing algorithm works, but I've found other configurations are more ideal in other more complicated cases.

![image](https://github.com/CadQuery/OCP/assets/55867501/a55f77c7-446d-4054-9624-d7a5343aedce)

**Comment by adam-urbanczyk** [comment]
I just merged a fix. Could confirm (once the build is available via the cadquery conda channel) that this solves your issue.
