### ISSUE TITLE
Requesting New Alpha-Beta Release

### ISSUE THREAD

**Issue by jmwright** [CadQuery/OCP#18]
Would it be possible to get a new release, even if it's still a pre-release? It's to solve the issue with the FreeBSD ports system compiled version not working because of using the outdated alpha release.

https://groups.google.com/d/msg/cadquery/lFQ-3_gZ2cI/3a_cGH22AAAJ

**Comment by adam-urbanczyk** [comment]
Solved: https://github.com/CadQuery/OCP/releases/tag/7.4-RC1

**Comment by jmwright** [comment]
Thanks @adam-urbanczyk !
