### ISSUE TITLE
Compiling 7.5 from sources

### ISSUE THREAD

**Issue by bragostin** [CadQuery/OCP#35]
I was trying to compile from sources on Debian 10 following the same procedure as in #19 using 
`cmake -B build_dir -S src_dir -G Ninja && cmake --build build_dir`
but there does not seem to be a `CMakeLists.txt` in OCP-7.5-RC1.
I tried using that of OCP_src_Ubuntu-16.04 in 7.4-RC2 but it does not work.
I imagine the compiling procedure has changed?

**Comment by adam-urbanczyk** [comment]
Nothing changed AFAIK. What are the steps to reproduce this?

**Comment by bragostin** [comment]
From the OCP-7.5-RC1 directory and after creating the `build` directory
`cmake -B build -S . -G Ninja && cmake --build build
CMake Error: The source directory "/home/bruno/Downloads/CadQuery/OCP_7.5/OCP-7.5-RC1" does not appear to contain CMakeLists.txt.`
With 7.4 `CMakeLists.txt` was present in the source directory and compiling worked fine after modifying some paths to required libraries to suit my local installation.

**Comment by adam-urbanczyk** [comment]
OK I understand what you mean now. Nothing changed but I did not attach manually the generated sources (there is one manually added file in 7.4 but non in 7.5). If you want to build right away you need generate them using pywrap.

**Comment by adam-urbanczyk** [comment]
Here are some pointers: https://github.com/CadQuery/OCP/issues/27#issuecomment-705101291

**Comment by bragostin** [comment]
I close this one because I ran into the exact same issues as #27 and was not able to solve them. 
However I finally installed a miniconda environment (which can be done through Debian apt package manager nowadays) and I now have OCP 7.5 installed and it did not break my native Debian python environment. So hurrah!

**Comment by adam-urbanczyk** [comment]
Glad to hear. For my info, what was blocking for you regarding compilation?

**Comment by bragostin** [comment]
In the end I get the same error message than in #27 
```
[367/368] Building CXX object CMakeFiles/OCP.dir/math_pre.cpp.o
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by bragostin** [comment]
Although, I just noticed, installing OCP 7.5 conda downgraded cadquery master to cadquery 2.0...
Looks like I can have cadquery master only with OCP 7.4.
Is that to be expected?

**Comment by adam-urbanczyk** [comment]
Yes, for now CQ does not work with 7.5. You 'd have to edit it by hand here and there.

**Comment by bragostin** [comment]
That's right. For the record I did the following steps to have OCP 7.5 working with Cadquery master:
```
conda install --no-deps -c conda-forge -c cadquery ocp=7.5
conda install --no-deps -c conda-forge -c cadquery occt=7.5
```
and comment line 151 of shapes.py (`Font_BRepTextBuilder,`)

**Comment by adam-urbanczyk** [comment]
Yes, AFAIR text related functionality needs fixing.
