### ISSUE TITLE
Long-Term Plans

### ISSUE THREAD

**Issue by jmwright** [CadQuery/OCP#4]
@adam-urbanczyk With the imminent release of PythonOCC 7.4.0, what are the long-term plans for OCP? Are we planning to switch the CQ 2.0 codebase over to OCP, or will it simply remain an alternative to PythonOCC?

**Comment by adam-urbanczyk** [comment]
I'd say it is still open. I see the following advantages:
* Faster tracking of OCCT (NB: 7.3 --> 7.4 conversion was really quick)
* More complete API
* More control, CQ specific solutions
* Modern binding technology (libclang+pybind11 vs SWIG)

Disadvantages:
* Additional work

I personally think it makes sense to go for it and I'm willing to do the work. But on the other hand I'd prefer not to push my opinion on everyone. I asked if the PythonOCC folks are willing to update their binding technology to pybind11 but that does not seem the case. I did contribute a couple of lines to PythonOCC but in general I'd rather spend time sharpening my `pybind11` i.so. `SWIG` skills.

What is your take on it?

**Comment by jmwright** [comment]
I can certainly see the advantages you mention above. Some people may see the lack of display functionality like PythonOCC has as a disadvantage. Personally, I see it as an advantage for CQ. The core of CQ should only concerned with generating the models. It's the execution environment's (CQ-editor, jupyter-cadquery, etc) responsibility to display the models. If someone really wanted to, they could add PythonOCC and Qt/wx to their environment and display their CQ models that way.

I definitely like the idea of being in control of our own bindings, and not depending on another project who's priorities may differ from ours. I'm not knocking the PythonOCC devs. I think PythonOCC is great. It would just be nice to have the upgrade speed, control and flexibility that custom bindings give us.

**Comment by adam-urbanczyk** [comment]
In the meantime I got Windows and Mac builds working:

https://github.com/CadQuery/OCP/releases/tag/7.4-alpha

**Comment by frmdstryr** [comment]
Just found this repo, looks great! 

Are there any plans on releasing it on conda and/or pypi?

**Comment by adam-urbanczyk** [comment]
Yes, definitely conda package, maybe a wheel. You could be also interested in the project that generates OCP https://github.com/CadQuery/pywrap .

**Comment by frmdstryr** [comment]
Sounds great! Once it's released I'd like to give it a try.

Yes I saw pywrap as well, looks similar to how [OCCT](https://github.com/LaughlinResearch/pyOCCT) does it, although that project seems to have stopped development.

**Comment by adam-urbanczyk** [comment]
Pywrap/OCP was actually inspired by pyOCCT. I started working on pywrap before pyOCCT_binder was open sourced.

**Comment by adam-urbanczyk** [comment]
CQ is based on OCP now and is a conda package provided. The ambition is to switch to OCCT 7.5 when it is released.
