### ISSUE TITLE
7.6 Release?

### ISSUE THREAD

**Issue by whophil** [CadQuery/OCP#85]
Is there work to be done before an official 7.6 release?

**Comment by whophil** [comment]
@adam-urbanczyk any thoughts on this? The conda-forge OCP feedstock depends on an official GitHub release on this repo

**Comment by adam-urbanczyk** [comment]
My plan was to release this after CQ 2.2 release + some additional time for testing.

**Comment by adam-urbanczyk** [comment]
@whophil plans do change, so there you go: https://github.com/CadQuery/OCP/releases/tag/7.6.3.0

**Comment by whophil** [comment]
Thanks @adam-urbanczyk ! If you could provide the binding code as release artifacts as you did with 7.5.3 (e.g., [OCP_src_ubuntu-18.04.zip](https://github.com/CadQuery/OCP/releases/download/7.5.3.0/OCP_src_ubuntu-18.04.zip), I can start the conda-forge build.

**Comment by adam-urbanczyk** [comment]
Done
