### ISSUE TITLE
BRepGProp::LinearProperties missing in the OSX version

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/OCP#9]
The function seems to be removed in the "filter" step, it is present before. In the filter step I assumed that name mangling is the same on linux and OSX  check if this assumption always hold.

**Comment by jmwright** [comment]
Reference: https://github.com/CadQuery/cadquery/issues/302#issuecomment-610024628

**Comment by adam-urbanczyk** [comment]
Mangling seems to be slightly different:

OSX:
`__ZN9BRepGProp16LinearPropertiesERK12TopoDS_ShapeR12GProp_GPropsbb`
Linux:
`_ZN9BRepGProp16LinearPropertiesERK12TopoDS_ShapeR12GProp_GPropsbb`

**Comment by adam-urbanczyk** [comment]
Solved in the latest version, see this dummy PR for confirmation: https://github.com/CadQuery/cadquery/pull/329
