### ISSUE TITLE
Update process / Where to achieve compatibility

### ISSUE THREAD

**Issue by kiufta** [CadQuery/OCP#94]
How does the update process work? I would like to try out opencascade 7.7.0 without bothering you too much.

After doing this dirty trick before building OCP
```
  rm -rf ./opencascade
  rm -rf ./pywrap/opencascade
  ln -s /usr/include/opencascade .               [contains 7.7.0 headers]
```
how can there be errors? Where do they come from?

**Comment by adam-urbanczyk** [comment]
You'll need to figure it out on your own based one the CI pipeline. Expect no support.
