### ISSUE TITLE
pickle OCP objects

### ISSUE THREAD

**Issue by ns6022** [CadQuery/OCP#95]
Firstly - thank you very much for the work that you have put into this project.

Previously I have used PythonOCC (bindings generated with SWIG) which allows objects to be pickled e.g. https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_shape_pickling.py

When pickling OCP objects, I receive the following error:
TypeError: cannot pickle 'OCP.TopoDS.TopoDS_Shape' object

Are there plans to enable pickling using Pybind11?
https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support

Many thanks.

**Comment by adam-urbanczyk** [comment]
Hey, no plans to implement it. This is a duplicate of #48. TL;DR use the brep format for (de)serializing TopoDS_Shape objects.
