### ISSUE TITLE
 cadquery-ocp 7.6.3a0 not working on Windows 7

### ISSUE THREAD

**Issue by polycorn** [CadQuery/OCP#98]
The cadquery-ocp 7.6.3a0 version included a compiled vtk 9.1, which used the tbb12-XXX.dll. This dll had a call to Kernel32.dll for function "GetCurrentThreadStackLimits", and windows7 does not have it. It is only available on Windows 8+.
The offical vtk 9.1 package does not have this depenedency, thus, it can be executed on windows 7.
The old cadquery-ocp 7.5.3.0's tbb dll does not have this function call.

**Comment by adam-urbanczyk** [comment]
Cadquery-OCP is not maintained here. Please open an issue here: https://github.com/CadQuery/ocp-build-system
